# Generated by Django 3.2.5 on 2021-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closest_pair', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=30)),
                ('input_str', models.TextField()),
            ],
            options={
                'ordering': ['input_str'],
            },
        ),
    ]
